const MOCK_ACCOUNT_USERNAME = 'gdeiassistant'
const MOCK_ACCOUNT_PASSWORD = 'gdeiassistant'
const MOCK_CREDENTIALS_HINT = `Mock 账号：${MOCK_ACCOUNT_USERNAME} / ${MOCK_ACCOUNT_PASSWORD}`

module.exports = {
  MOCK_ACCOUNT_USERNAME,
  MOCK_ACCOUNT_PASSWORD,
  MOCK_CREDENTIALS_HINT
}
