const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '..')
const locales = ['zh-CN', 'zh-HK', 'zh-TW', 'en', 'ja', 'ko']
const messages = {}

locales.forEach(function (locale) {
  messages[locale] = JSON.parse(
    fs.readFileSync(path.join(root, 'locales', locale + '.json'), 'utf8')
  )
})

const outputPath = path.join(root, 'locales/messages.generated.js')
const output =
  '// Generated by scripts/generate-locales.js from locales/*.json. Do not edit directly.\n' +
  'module.exports = ' +
  JSON.stringify(messages, null, 2) +
  '\n'

if (process.argv.includes('--check')) {
  if (!fs.existsSync(outputPath) || fs.readFileSync(outputPath, 'utf8') !== output) {
    console.error('Generated locale messages are outdated. Run npm run locales:generate.')
    process.exitCode = 1
  } else {
    console.log('Generated locale messages match all six JSON catalogs.')
  }
} else {
  fs.writeFileSync(outputPath, output)
  console.log('Generated locale messages for ' + locales.length + ' languages.')
}
